export const filterData = [
  //   {
  //     id: 5,
  //     title: "Customer Reviews",
  //     key: "reviews",
  //     type: "radio",
  //     data: [
  //       { id: 1, title: "", slug: "5" },
  //       { id: 2, title: "", slug: "4" },
  //       { id: 3, title: "", slug: "3" },
  //       { id: 4, title: "", slug: "2" },
  //       { id: 5, title: "", slug: "1" },
  //       { id: 6, title: "No review", slug: "no_rating" },
  //     ],
  //   },
  {
    id: 6,
    title: "Discount",
    key: "discount",
    type: "radio",
    data: [
      { id: 1, title: "90% off or more", slug: "90" },
      { id: 2, title: "80% off or more", slug: "80" },
      { id: 3, title: "70% off or more", slug: "70" },
      { id: 4, title: "60% off or more", slug: "60" },
      { id: 5, title: "50% off or more", slug: "50" },
      { id: 6, title: "40% off or more", slug: "40" },
      { id: 7, title: "30% off or more", slug: "30" },
    ],
  },
  {
    id: 8,
    title: "Price",
    key: "price_range",
    type: "radio",
    data: [
      { id: 1, title: "Under £10", slug: "0-10" },
      { id: 2, title: "£10 - £25", slug: "10-25" },
      { id: 3, title: "£25 - £50", slug: "25-50" },
      { id: 4, title: "£50 - £100", slug: "50-100" },
      { id: 5, title: "Over £100", slug: "100-0" },
      // { id: 6, title: "", slug: "min_max" },
    ],
  },
];
